### ISSUE TITLE
Replace CentOS with RHEL9

### ISSUE THREAD

**Issue by WhileDekker** [zscaler/terraform-azurerm-zpa-private-service-edge-modules#15]
Hey,

CentOS7 is eol and Zscaler has recently released ova's and cloud images for most of their products. Can you share or update the SKUs for using RHEL 9 image for the PSE via tf in your examples as those are still pointing to the old CentOS. 

Thanks Alex

**Comment by willguibr** [comment]
Work is in progress.

**Comment by willguibr** [comment]
Latest v1.1.0 version has been updated to RHEL9.
Zscaler DevRel
